"""Remove username from User table

Revision ID: ce6dcf39ddaa
Revises: 6536f497f19c
Create Date: 2024-08-19 23:15:22.142207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce6dcf39ddaa'
down_revision = '6536f497f19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
